# Generated by Django 5.2.9 on 2026-01-01 03:45

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataSetArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload the training data set here.', upload_to='training_data_set/', validators=[app.models.validate_zip_file])),
                ('archive_extracted', models.BooleanField(default=False)),
                ('date_archive_extracted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the training data set.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Data Set File',
                'verbose_name_plural': 'Training Data Set Files',
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_series_uid', models.CharField(blank=True, help_text='Image DICOM Series UID', max_length=255, null=True, unique=True)),
                ('number_of_images', models.IntegerField(blank=True, help_text='Number of images in the series', null=True)),
                ('patient_id', models.CharField(blank=True, help_text='Patient ID', max_length=255, null=True)),
                ('series_description', models.CharField(blank=True, help_text='Series Description', max_length=255, null=True)),
                ('series_acquisition_date', models.DateField(blank=True, help_text='Series Acquisition Date', null=True)),
                ('image_type', models.CharField(blank=True, choices=[('ct', 'CT'), ('mr', 'MR'), ('pt', 'PT')], help_text='Image Type', max_length=255, null=True)),
                ('image_paths', models.JSONField(blank=True, help_text='Image paths for the series.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_data_set_archive', models.ForeignKey(help_text='Training data set archive to be used for training', on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingdatasetarchive')),
            ],
            options={
                'verbose_name': 'Training Image',
                'verbose_name_plural': 'Training Images',
            },
        ),
        migrations.CreateModel(
            name='TrainingRTStructureSetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structureset_dicom_series_uid', models.CharField(blank=True, help_text='This is the series instance UID of the RTStructureSet File itself.', max_length=255, null=True, unique=True)),
                ('structureset_path', models.CharField(blank=True, help_text='Path of the RTStructureSet file.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referenced_series_instance_uid', models.ForeignKey(help_text='Referenced Series Instance UID. This is obtained from the DICOM file metadata. The UID is available as a nested tag with the following path: Referenced Frame of Reference Sequence > RT Referenced Study Sequence > RT Referenced Series Sequence > Series Instance UID. This UID is also used to link the RTStructureSet file with the corresponding image.', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingimage')),
            ],
            options={
                'verbose_name': 'Training Data RTStructureSet',
                'verbose_name_plural': 'Training Data RTStructureSets',
            },
        ),
        migrations.CreateModel(
            name='TrainingRTPlanAndDoseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtdose_series_instance_uid', models.CharField(help_text='Series Instance UID of the RTDose file.', max_length=255)),
                ('rtdose_path', models.CharField(blank=True, help_text='Path of the RTDose file.', null=True)),
                ('rtplan_series_instance_uid', models.CharField(help_text='Series Instance UID of the RTPlan file.', max_length=255)),
                ('rtplan_path', models.CharField(blank=True, help_text='Path of the RTPlan file.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structureset_referenced_series_intance_uid', models.ForeignKey(help_text='The RT Structure Set to which the RT Plan and Dose belong to. This information is available in the Referenced Structure Set Sequence > Referenced SOP Instance UID.', on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingrtstructuresetfile')),
            ],
            options={
                'verbose_name': 'Training Data RTPlan and RTDose Pair',
                'verbose_name_plural': 'Training Data RTPlan and RTDose Pairs',
            },
        ),
        migrations.CreateModel(
            name='TrainingRTStructureSetROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_name', models.CharField(blank=True, help_text='ROI Name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_rt_structure_set', models.ForeignKey(help_text='The RT Structure Set to which the ROI belongs to', on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingrtstructuresetfile')),
            ],
            options={
                'verbose_name': 'Training Data RTStructureSet ROI',
                'verbose_name_plural': 'Training Data RTStructureSet ROIs',
            },
        ),
    ]
