# Generated by Django 5.2.9 on 2026-01-02 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_model', models.CharField(help_text='Name of the model.', max_length=255)),
                ('type_of_model', models.CharField(choices=[('svmr', 'Support Vector Machine Regression'), ('xgbr', 'XGBoost'), ('ann', 'Artificial Neural Networks')], help_text='Type of model to be used for training.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_template', models.ForeignKey(help_text='Prescription template to be used for training.', on_delete=django.db.models.deletion.CASCADE, to='app.prescriptiontemplate')),
                ('rt_plan_dose_file', models.ManyToManyField(help_text='RTPlan and RTDose file to be used for training.', to='trainer.trainingrtplananddosefile')),
            ],
            options={
                'verbose_name': 'Prediction Model',
                'verbose_name_plural': 'Prediction Models',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(help_text='Model file in a serialized format like pickle or onnx or gguf format.', upload_to='model_files/')),
                ('model_version', models.DecimalField(decimal_places=2, help_text='Version of the model file.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction_model', models.OneToOneField(help_text='Prediction model to which the model file belongs to.', on_delete=django.db.models.deletion.CASCADE, to='trainer.predictionmodel')),
            ],
            options={
                'verbose_name': 'Prediction Model File',
                'verbose_name_plural': 'Prediction Model Files',
            },
        ),
    ]
