# Generated by Django 5.2.9 on 2025-12-29 10:03

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(help_text='DICOM Series Instance UID extracted from the DICOM data.', max_length=255, unique=True)),
                ('frame_of_reference_uid', models.CharField(blank=True, help_text='Frame of Reference UID extracted from the DICOM data.', max_length=255, null=True)),
                ('series_description', models.CharField(blank=True, help_text='Series Description tag data extracted from the DICOM data', max_length=255, null=True)),
                ('series_date', models.DateField(blank=True, help_text='Series Date tag data extracted from the DICOM data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DICOM Series',
            },
        ),
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(help_text='DICOM Study Instance UID extracted from the DICOM data.', max_length=255, unique=True)),
                ('study_description', models.CharField(blank=True, help_text='Study Description tag data extracted from the DICOM data', max_length=255, null=True)),
                ('study_date', models.DateField(blank=True, help_text='Study Date tag data extracted from the DICOM data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DICOM Studies',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_patient_id', models.CharField(help_text='Unique Patient ID extracted from DICOM data', max_length=255, unique=True)),
                ('patient_name', models.CharField(blank=True, help_text='Patient Name extracted from DICOM data', max_length=255, null=True)),
                ('patient_dob', models.DateField(blank=True, help_text='Patient DOB extracted from DICOM data', null=True)),
                ('patient_sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Patient Sex extracted from DICOM data. This is then matched to the Gender choices', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the prescription template', max_length=255, unique=True)),
                ('cancer_site', models.CharField(blank=True, help_text='Cancer site. Select from the list or provide your own', max_length=255, null=True)),
                ('cancer_side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('midline', 'Midline'), ('bilateral', 'Bilateral'), ('not_applicable', 'Not Applicable')], help_text='Side of the disease. Select from the list.', max_length=255, null=True)),
                ('treatment_modality', models.CharField(blank=True, choices=[('EBRT', 'External Beam Radiotherapy'), ('Electron', 'Electron'), ('Proton', 'Proton'), ('Carbon', 'Carbon Ion'), ('Brachytherapy', 'Brachytherapy')], help_text='Treatment modality. Select from the list.', max_length=255, null=True)),
                ('ebrt_beam_energy', models.DecimalField(blank=True, decimal_places=2, help_text='Beam energy to be used in MV for EBRT', max_digits=4, null=True)),
                ('electron_beam_energy', models.DecimalField(blank=True, decimal_places=2, help_text='Beam energy to be used in MeV for Electron Therapy', max_digits=4, null=True)),
                ('proton_beam_energy', models.DecimalField(blank=True, decimal_places=2, help_text='Beam energy to be used in MeV for Proton Therapy', max_digits=4, null=True)),
                ('carbon_beam_energy', models.DecimalField(blank=True, decimal_places=2, help_text='Beam energy to be used in MeV for Carbon Ion Therapy', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Prescription Template',
            },
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulegroup_name', models.CharField(help_text='Name of the rulegroup', max_length=255, unique=True)),
                ('rulegroup_description', models.TextField(blank=True, help_text='Description of the rulegroup', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rule Groups',
            },
        ),
        migrations.CreateModel(
            name='DICOMFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload the DICOM file here.', upload_to='dicom_files', validators=[app.models.validate_zip_file])),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status of the DICOM file.', max_length=255)),
                ('date_processing_completed', models.DateTimeField(blank=True, help_text='Date and time when the processing is completed successfully.', null=True)),
                ('processing_log_data', models.JSONField(blank=True, help_text='Processing log data stored after processing is completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the DICOM file. Please upload a single ZIP file.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DICOM Files',
            },
        ),
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(help_text='DICOM SOP Instance UID extracted from the DICOM data.', max_length=255, unique=True)),
                ('modality', models.CharField(blank=True, help_text='Modality tag data extracted from the DICOM data', max_length=10, null=True)),
                ('pixel_spacing', models.CharField(blank=True, help_text='Pixel Spacing tag data extracted from the DICOM data', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_series', models.ForeignKey(help_text='DICOM Series ID to which the DICOM instance refers to.', on_delete=django.db.models.deletion.CASCADE, to='app.dicomseries')),
            ],
            options={
                'verbose_name_plural': 'DICOM Instances',
            },
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='dicom_study',
            field=models.ForeignKey(help_text='DICOM Study ID to which the DICOM series refers to.', on_delete=django.db.models.deletion.CASCADE, to='app.dicomstudy'),
        ),
        migrations.CreateModel(
            name='ImageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_location', models.DecimalField(blank=True, decimal_places=5, help_text='The Slice Location value extracted from the DICOM data', max_digits=15, null=True)),
                ('pixel_spacing', models.JSONField(blank=True, help_text='Pixel spacing value obtained from the DICOM file. The two values represent the distance between the center of the pixels in the row and column respectively.', null=True)),
                ('slice_thickness', models.DecimalField(blank=True, decimal_places=5, help_text='Slice thickness values obtained from the DICOM file', max_digits=15, null=True)),
                ('patient_position', models.CharField(blank=True, help_text='Patient Position tag data extracted from the DICOM data', max_length=255, null=True)),
                ('image_position_patient', models.JSONField(blank=True, help_text='Image Position (Patient) tag data extracted from the DICOM data. It refers to the x, y, and z coordinates of the upper left hand corner of the image; it is the center of the first voxel transmitted', null=True)),
                ('image_orientation_patient', models.JSONField(blank=True, help_text='Image Orientation (Patient) tag data extracted from the DICOM data. It specifies the direction cosines of the first row and the first column with respect to the patient. These Attributes shall be provide as a pair. Row value for the x, y, and z axes respectively followed by the Column value for the x, y, and z axes respectively.', null=True)),
                ('instance_number', models.IntegerField(blank=True, help_text='Instance Number tag data extracted from the DICOM data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_instance', models.OneToOneField(help_text='The DICOM Instance ID of the image referenced.', on_delete=django.db.models.deletion.CASCADE, to='app.dicominstance')),
            ],
            options={
                'verbose_name_plural': 'Image Information',
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(help_text='Patient ID to which the DICOM study refers to.', on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.CreateModel(
            name='RTStructureSetInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_roi', models.IntegerField(blank=True, help_text='Number of ROIs in the RTStructureSet', null=True)),
                ('referenced_frame_of_reference_uid', models.CharField(blank=True, help_text='Referenced Frame of Reference UID tag data extracted from the RTStructureSet data', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_instance', models.OneToOneField(help_text='DICOM Instance ID for the ROI obtained from the RTStructureSet data', on_delete=django.db.models.deletion.CASCADE, to='app.dicominstance')),
                ('prescription_template_id', models.ForeignKey(blank=True, help_text='Prescription Template ID to which the RTStructureSet belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prescriptiontemplate')),
            ],
            options={
                'verbose_name_plural': 'RT Structure Set Information',
            },
        ),
        migrations.CreateModel(
            name='RTStructureROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_number', models.IntegerField(help_text='ROI Number tag data extracted from the RTStructureSet data')),
                ('roi_name', models.CharField(help_text='ROI Name tag data extracted from the RTStructureSet data', max_length=255)),
                ('roi_contour_data', models.JSONField(help_text='ROI Contour Data tag data extracted from the RTStructureSet data along with corresponding Referenced SOP Instance UID values for each Referenced SOP Instance UID. This will be stored as a tuple.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rt_structure_set', models.ForeignKey(help_text='RTStructureSet Information ID for the ROI obtained from the RTStructureSet data', on_delete=django.db.models.deletion.CASCADE, to='app.rtstructuresetinformation')),
            ],
            options={
                'verbose_name_plural': 'RT Structure Regions of Interest',
            },
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='rulegroup_name',
            field=models.OneToOneField(help_text='Rulegroup to which the prescription template belongs to', on_delete=django.db.models.deletion.CASCADE, to='app.rulegroup'),
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleset_order', models.PositiveIntegerField(help_text='Order of the ruleset. Rulesets will be evaluated in the numerical order specified with lower value numbers being evaluated first.')),
                ('ruleset_name', models.CharField(help_text='Name of the ruleset', max_length=255, unique=True)),
                ('ruleset_combination', models.CharField(blank=True, help_text='Defines how this ruleset should be combined with the other rulesets in the same rulegroup', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rulegroup', models.ForeignKey(help_text='Rulegroup to which the ruleset belongs to', on_delete=django.db.models.deletion.CASCADE, to='app.rulegroup')),
            ],
            options={
                'verbose_name_plural': 'Rule Sets',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_order', models.PositiveIntegerField(help_text='Order of the rule. Rules will be evaluated in the numerical order specified with lower value numbers being evaluated first.')),
                ('parameter_to_be_matched', models.CharField(blank=True, choices=[('roi_name', 'ROI Name'), ('modality', 'Modality'), ('structure_set_label', 'Structure Set Label'), ('study_description', 'Study Description'), ('series_description', 'Series Description'), ('patients_sex', "Patient's Sex"), ('approval_status', 'Approval Status')], help_text='Parameter to be matched. Select from the list or provide your own', max_length=255, null=True)),
                ('matching_operator', models.CharField(blank=True, choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('string_contains_case_insensitive', 'String Contains Case Insensitive'), ('string_contains_case_sensitive', 'String Contains Case Sensitive'), ('string_does_not_contain_case_insensitive', 'String Does Not Contain Case Insensitive'), ('string_does_not_contain_case_sensitive', 'String Does Not Contain Case Sensitive'), ('greater_than', 'Greater Than'), ('greater_than_or_equal_to', 'Greater Than Or Equal To'), ('less_than', 'Less Than'), ('less_than_or_equal_to', 'Less Than Or Equal To')], help_text='Matching operator to be used. Select from the list or provide your own', max_length=255, null=True)),
                ('matching_value', models.CharField(blank=True, help_text='Matching value to be used for the matching', max_length=255, null=True)),
                ('rule_combination_type', models.CharField(blank=True, choices=[('and', 'And'), ('or', 'Or')], help_text='How should the rule be combined with other rules in the ruleset.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruleset', models.ForeignKey(help_text='Ruleset to which the rule belongs to', on_delete=django.db.models.deletion.CASCADE, to='app.ruleset')),
            ],
            options={
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_name', models.CharField(help_text='ROI Name to be matched to RTStructureSet', max_length=255)),
                ('dose_prescribed', models.DecimalField(decimal_places=3, help_text='Dose prescribed', max_digits=7)),
                ('dose_unit', models.CharField(choices=[('Gy', 'Gy'), ('cGy', 'cGy')], default='Gy', max_length=10)),
                ('fractions_prescribed', models.IntegerField(help_text='Number of fractions prescribed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_template', models.ForeignKey(help_text='Prescription Template ID to which the prescription belongs to', on_delete=django.db.models.deletion.CASCADE, to='app.prescriptiontemplate')),
            ],
            options={
                'verbose_name_plural': 'Prescriptions',
                'constraints': [models.UniqueConstraint(fields=('prescription_template_id', 'roi_name'), name='unique_prescription_template_roi_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('rulegroup', 'ruleset_order'), name='unique_rulegroup_ruleset_order'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(fields=('ruleset', 'rule_order'), name='unique_ruleset_rule_order'),
        ),
    ]
